name: .NET Core Console

on:
  push:
  pull_request:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [macos-latest, ubuntu-latest]
        cache: [true, false]

    runs-on: ${{ matrix.os }}


    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      cache: ${{ matrix.cache }}
      with:
        dotnet-version: 6.0.x

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore

    - name: Build the application
      run: dotnet build -c $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

